version: 2

models:
  - name: daily_avg_weather_trend
    columns:
      - name: city_id
        tests:
          - not_null
      - name: weather_date
        tests:
          - not_null
      - name: avg_temp_fahrenheit
        tests:
          - not_null
      - name: avg_humidity
        tests:
          - not_null
